export type ModuleDef = {
  id: string;
  label: string;
  path: string;
  roles: Array<"ADMIN"|"SELLER">;
  entitlements?: string[];
};

export const MODULES: ModuleDef[] = [
  // === ADMIN MODULES ===
  { id: "admin-dashboard", label: "Ana Kontrol Paneli", path: "/admin/dashboard", roles: ["ADMIN"] },
  { id: "admin-analytics", label: "Analitik", path: "/admin/analytics", roles: ["ADMIN"] },
  { id: "admin-reports", label: "Raporlar", path: "/admin/reports", roles: ["ADMIN"] },
  { id: "admin-sellers", label: "Satıcı Yönetimi", path: "/admin/sellers", roles: ["ADMIN"] },
  { id: "admin-users", label: "Kullanıcı Yönetimi", path: "/admin/users", roles: ["ADMIN"] },
  { id: "admin-orders", label: "Sipariş Yönetimi", path: "/admin/commerce/orders", roles: ["ADMIN"] },
  { id: "admin-products", label: "Ürün Yönetimi", path: "/admin/products", roles: ["ADMIN"] },
  { id: "admin-inventory", label: "Envanter", path: "/admin/commerce/inventory", roles: ["ADMIN"] },
  { id: "admin-shipping", label: "Kargo Yönetimi", path: "/admin/commerce/shipping", roles: ["ADMIN"] },
  { id: "admin-returns", label: "İade Yönetimi", path: "/admin/commerce/returns", roles: ["ADMIN"] },
  { id: "admin-settlements", label: "Ödeme Yönetimi", path: "/admin/commerce/settlements", roles: ["ADMIN"] },
  { id: "admin-seller-payments", label: "Satıcı Ödemeleri", path: "/admin/commerce/seller-payments", roles: ["ADMIN"] },
  { id: "admin-risk", label: "Risk Analizi", path: "/admin/commerce/risk", roles: ["ADMIN"] },
  { id: "admin-domains", label: "Domain Yönetimi", path: "/admin/commerce/domains", roles: ["ADMIN"] },
  { id: "admin-marketing", label: "Pazarlama", path: "/admin/marketing", roles: ["ADMIN"] },
  { id: "admin-campaigns", label: "Kampanya Yönetimi", path: "/admin/marketing/campaigns", roles: ["ADMIN"] },
  { id: "admin-coupons", label: "Kupon Yönetimi", path: "/admin/marketing/coupons", roles: ["ADMIN"] },
  { id: "admin-promotions", label: "Promosyon Yönetimi", path: "/admin/marketing/promotions", roles: ["ADMIN"] },
  { id: "admin-crm", label: "Müşteri İlişkileri", path: "/admin/marketing/crm", roles: ["ADMIN"] },
  { id: "admin-customer-relations", label: "Müşteri İlişkileri", path: "/admin/marketing/customer-relations", roles: ["ADMIN"] },
  { id: "admin-segmentation", label: "Segmentasyon", path: "/admin/marketing/segmentation", roles: ["ADMIN"] },
  { id: "admin-segments", label: "Segmentler", path: "/admin/marketing/segments", roles: ["ADMIN"] },
  { id: "admin-metrics", label: "Pazarlama Metrikleri", path: "/admin/marketing/metrics", roles: ["ADMIN"] },
  { id: "admin-ab-testing", label: "A/B Test", path: "/admin/marketing/ab-testing", roles: ["ADMIN"] },
  { id: "admin-ab-tests", label: "A/B Testler", path: "/admin/marketing/ab-tests", roles: ["ADMIN"] },
  { id: "admin-ads", label: "Reklam Yönetimi", path: "/admin/marketing/ads", roles: ["ADMIN"] },
  { id: "admin-ai", label: "AI Araçları", path: "/admin/ai", roles: ["ADMIN"] },
  { id: "admin-ai-keyword", label: "Anahtar Kelime Analiz", path: "/admin/ai/keyword-explorer", roles: ["ADMIN"] },
  { id: "admin-ai-automation", label: "AI Otomasyon", path: "/admin/ai/automation", roles: ["ADMIN"] },
  { id: "admin-ai-market-intelligence", label: "Pazar Zekası", path: "/admin/ai/market-intelligence", roles: ["ADMIN"] },
  { id: "admin-ai-predictions", label: "Gelecek Tahminleri", path: "/admin/ai/predictions", roles: ["ADMIN"] },
  { id: "admin-ai-price-suggestion", label: "Fiyat Önerisi", path: "/admin/ai/price-suggestion", roles: ["ADMIN"] },
  { id: "admin-ai-seo-assistant", label: "SEO Asistanı", path: "/admin/ai/seo-assistant", roles: ["ADMIN"] },
  { id: "admin-ai-trend-analysis", label: "Trend Analizi", path: "/admin/ai/trend-analysis", roles: ["ADMIN"] },
  { id: "admin-ai-vat-assistant", label: "KDV Asistanı", path: "/admin/ai/vat-assistant", roles: ["ADMIN"] },
  { id: "admin-ai-visual-quality", label: "Görsel Kalite", path: "/admin/ai/visual-quality", roles: ["ADMIN"] },
  { id: "admin-accounting", label: "Muhasebe", path: "/admin/accounting", roles: ["ADMIN"] },
  { id: "admin-accounting-ai-assistant", label: "AI Muhasebe Asistanı", path: "/admin/accounting/ai-assistant", roles: ["ADMIN"] },
  { id: "admin-accounting-ap", label: "Borç Hesapları", path: "/admin/accounting/ap", roles: ["ADMIN"] },
  { id: "admin-accounting-ar", label: "Alacak Hesapları", path: "/admin/accounting/ar", roles: ["ADMIN"] },
  { id: "admin-accounting-assets", label: "Sabit Kıymetler", path: "/admin/accounting/assets", roles: ["ADMIN"] },
  { id: "admin-accounting-banking", label: "Banka İşlemleri", path: "/admin/accounting/banking", roles: ["ADMIN"] },
  { id: "admin-accounting-chart", label: "Hesap Planı", path: "/admin/accounting/chart-of-accounts", roles: ["ADMIN"] },
  { id: "admin-accounting-fixed-assets", label: "Sabit Kıymetler", path: "/admin/accounting/fixed-assets", roles: ["ADMIN"] },
  { id: "admin-accounting-journals", label: "Yevmiye Defteri", path: "/admin/accounting/journals", roles: ["ADMIN"] },
  { id: "admin-accounting-taxes", label: "Vergi Yönetimi", path: "/admin/accounting/taxes", roles: ["ADMIN"] },
  { id: "admin-content", label: "İçerik Yönetimi", path: "/admin/content", roles: ["ADMIN"] },
  { id: "admin-content-approval", label: "İçerik Onay", path: "/admin/content/approval-workflows", roles: ["ADMIN"] },
  { id: "admin-content-blog", label: "Blog Kontrol", path: "/admin/content/blog-control", roles: ["ADMIN"] },
  { id: "admin-content-ugc", label: "UGC Blog Modülasyonu", path: "/admin/content/ugc-blog-moderation", roles: ["ADMIN"] },
  { id: "admin-content-user-generated", label: "Kullanıcı Üretimi İçerik", path: "/admin/content/user-generated-content", roles: ["ADMIN"] },
  { id: "admin-content-reports", label: "İçerik Raporları", path: "/admin/content/content-reports", roles: ["ADMIN"] },
  { id: "admin-system", label: "Sistem Yönetimi", path: "/admin/system", roles: ["ADMIN"] },
  { id: "admin-system-backup", label: "Veritabanı Yedekleri", path: "/admin/system/database-backups", roles: ["ADMIN"] },
  { id: "admin-system-logs", label: "Sistem Logları", path: "/admin/logs", roles: ["ADMIN"] },
  { id: "admin-system-permissions", label: "Yetki Yönetimi", path: "/admin/system/permissions", roles: ["ADMIN"] },
  { id: "admin-system-roles", label: "Rol Yönetimi", path: "/admin/system/roles", roles: ["ADMIN"] },
  { id: "admin-system-security", label: "Güvenlik Yönetimi", path: "/admin/system/security", roles: ["ADMIN"] },
  { id: "admin-system-security-monitoring", label: "Güvenlik İzleme", path: "/admin/system/security-monitoring", roles: ["ADMIN"] },
  { id: "admin-system-risk-analysis", label: "Risk Analizi", path: "/admin/system/risk-analysis", roles: ["ADMIN"] },
  { id: "admin-system-white-label", label: "White Label Domainler", path: "/admin/system/white-label-domains", roles: ["ADMIN"] },
  { id: "admin-developer", label: "Geliştirici Araçları", path: "/admin/developer", roles: ["ADMIN"] },
  { id: "admin-developer-api", label: "API Dokümantasyonu", path: "/admin/developer/api-docs", roles: ["ADMIN"] },
  { id: "admin-developer-automation", label: "İşlem Otomasyonu", path: "/admin/developer/automation", roles: ["ADMIN"] },
  { id: "admin-developer-plugins", label: "Eklentiler", path: "/admin/developer/plugins", roles: ["ADMIN"] },
  { id: "admin-developer-webhooks", label: "Webhook'lar", path: "/admin/developer/webhooks", roles: ["ADMIN"] },
  { id: "admin-developer-workflows", label: "İş Akışları", path: "/admin/developer/workflows", roles: ["ADMIN"] },
  { id: "admin-settings", label: "Ayarlar", path: "/admin/settings", roles: ["ADMIN"] },
  { id: "admin-security", label: "Güvenlik", path: "/admin/security", roles: ["ADMIN"] },
  { id: "admin-roles", label: "Roller", path: "/admin/roles", roles: ["ADMIN"] },
  { id: "admin-backup", label: "Yedekleme", path: "/admin/backup", roles: ["ADMIN"] },

  // === SELLER MODULES ===
  { id: "seller-dashboard", label: "Satıcı Paneli", path: "/seller/dashboard", roles: ["SELLER", "ADMIN"] },
  { id: "seller-products", label: "Ürünlerim", path: "/seller/products", roles: ["SELLER", "ADMIN"] },
  { id: "seller-orders", label: "Siparişlerim", path: "/seller/orders", roles: ["SELLER", "ADMIN"] },
  { id: "seller-apply", label: "Satıcı Başvurusu", path: "/seller/apply", roles: ["SELLER", "ADMIN"] },

  // === SPECIAL MODULES (Özel Modüller) ===
  { id: "fraud-detect", label: "Fraud Tespiti", path: "/admin/fraud", roles: ["ADMIN"] },
  { id: "seller-approval", label: "Satıcı Onaylama", path: "/admin/sellers", roles: ["ADMIN"] },
  { id: "keyword-tool", label: "Anahtar Kelime Analiz", path: "/(dashboard)/seller/tools/keyword", roles: ["SELLER", "ADMIN"], entitlements: ["keyword-tool"] },
  { id: "bulk-upload", label: "Toplu Yükleme", path: "/(dashboard)/seller/tools/bulk-upload", roles: ["SELLER", "ADMIN"], entitlements: ["bulk-upload"] },
  { id: "ads-campaigns", label: "Reklam Kampanyaları", path: "/(dashboard)/seller/ads", roles: ["SELLER", "ADMIN"], entitlements: ["ads"] },
  { id: "billing", label: "Abonelik & Faturalama", path: "/(dashboard)/seller/billing", roles: ["SELLER", "ADMIN"] },
  { id: "domain-subscriptions", label: "Domain Abonelikleri", path: "/(dashboard)/seller/settings/domain-subscriptions", roles: ["SELLER", "ADMIN"] },
  { id: "influencers", label: "Influencer Keşfet", path: "/(dashboard)/seller/influencers", roles: ["SELLER", "ADMIN"] },
  { id: "influencer-apply", label: "Influencer Başvurusu", path: "/(dashboard)/influencer/apply", roles: ["BUYER", "SELLER", "ADMIN"] },
  { id: "influencer-dashboard", label: "Influencer Paneli", path: "/(dashboard)/influencer/dashboard", roles: ["SELLER", "ADMIN"] },
  { id: "admin-influencers", label: "Influencer Yönetimi", path: "/(admin)/influencers", roles: ["ADMIN"] },
];
