version: '3.8'

services:
  # Ana Next.js Uygulaması
  tdc-website:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Veri klasörünü kalıcı hale getir
      - ./data:/app/data
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - tdc-network

  # Nginx Reverse Proxy (Opsiyonel)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL sertifikaları için
    depends_on:
      - tdc-website
    restart: unless-stopped
    networks:
      - tdc-network

  # PostgreSQL (Opsiyonel - Supabase yerine)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tdc_database
      - POSTGRES_USER=tdc_user
      - POSTGRES_PASSWORD=tdc_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - tdc-network

  # Redis Cache (Opsiyonel)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - tdc-network

volumes:
  postgres_data:
  redis_data:

networks:
  tdc-network:
    driver: bridge
